#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")" && pwd)"
FIXTURES_DIR="$ROOT_DIR/fixtures"

mkdir -p "$FIXTURES_DIR"

python3 - "$ROOT_DIR" <<'PY'
import json
import os
import pathlib
import stat
from datetime import datetime, timezone
import hashlib
import textwrap

root = pathlib.Path(os.sys.argv[1])
fixtures_dir = root / "fixtures"

assets = [
    "capsule.ops.branch_s.v1/Makefile",
    "capsule.ops.branch_s.v1/apply_and_seal.sh",
    "capsule.ops.branch_s.v1/reissue_branch_s.sh",
    "capsule.ops.branch_s.v1/revoke_branch_s.sh",
    "capsule.ops.branch_s.v1/lib/branch_s_common.sh",
    "capsule.ops.branch_s.v1/manifest.json",
    "capsule.ops.branch_s.v1/README.md",
    "capsules/capsule.prompt.designStudio.dual.v1.json",
    "capsules/capsule.metaagent.solf1.oneshot.v1.json",
    "capsules/capsule.scene.designStudio.v1.json",
    "capsules/runtime/templates/solf1_oneshot.tpl",
    "capsules/runtime/templates/design_studio_cinematic.tpl",
    "scripts/build_scrollstream_capsule_b.py",
]

def file_entry(path: pathlib.Path):
    if not path.is_file():
        raise FileNotFoundError(path)
    stat_info = path.stat()
    digest = hashlib.sha256(path.read_bytes()).hexdigest()
    rel = path.relative_to(root).as_posix()
    return {
        "path": rel,
        "bytes": stat_info.st_size,
        "mode": stat.S_IMODE(stat_info.st_mode),
        "sha256": digest,
        "modified": datetime.fromtimestamp(stat_info.st_mtime, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }

entries = []
for rel in assets:
    abs_path = root / rel
    entries.append(file_entry(abs_path))

snapshot = {
    "schema": "capsule.branch_s.snapshot.v1",
    "generated_at": "2024-10-07T00:00:00Z",
    "capsule_id": "capsule.prompt.designStudio.dual.v1",
    "epoch": "sentinel-100",
    "assets": entries,
    "notes": [
        "Snapshot generated by create_fixtures.sh",
        "Includes Branch-S toolkit manifests, scripts, and prompt capsules",
    ],
}

snapshot_path = fixtures_dir / "snapshot.json"
snapshot_path.write_text(json.dumps(snapshot, indent=2) + "\n", encoding="utf-8")

snapshot_digest = hashlib.sha256(snapshot_path.read_bytes()).hexdigest()

sha_path = fixtures_dir / "snapshot.json.meta.sha256"
sha_path.write_text(snapshot_digest + "\n", encoding="utf-8")

yaml_path = fixtures_dir / "snapshot.json.meta.yaml"
yaml_content = textwrap.dedent(f"""
    generator: create_fixtures.sh
    schema: capsule.branch_s.snapshot.v1
    generated_at: 2024-10-07T00:00:00Z
    capsule_id: capsule.prompt.designStudio.dual.v1
    epoch: sentinel-100
    asset_count: {len(entries)}
    snapshot_sha256: {snapshot_digest}
""")
yaml_path.write_text(yaml_content.lstrip(), encoding="utf-8")
PY

printf 'Snapshot fixture created in %s\n' "$FIXTURES_DIR"
